### PR TITLE
Add non-strict-config flag

### PR DESCRIPTION
**Pull request by joostjager**
Bring back strict config parsing.

Non-strict parsing was introduced in https://github.com/bottlepay/lnmux/pull/48.

### CODE REVIEW

**Comment by Torakushi** [comment]
LGTM!

**Review by Torakushi — APPROVED** [review]
LGTM!

**Comment by joostjager** [comment]
Updated PR to make it a global flag rather than a per-command one.

**Review by Torakushi — APPROVED** [review]
LGTM

**Pull request merged**
